### ISSUE TITLE
High severity CVE related with go stdlib version

### ISSUE THREAD

**Issue by ikheifets-splunk** [goss-org/goss#903] opened 2024-05-09 11:41 UTC
**Describe the bug**
High severity CVE
<img width="1036" alt="Screenshot 2024-05-09 at 13 35 42" src="https://github.com/goss-org/goss/assets/138466237/7e2c18b2-2359-4cab-aa86-fe735027f126">

**How To Reproduce**
https://github.com/aquasecurity/trivy detected this CVE

**Expected Behavior**
using Go version without CVE

**Actual Behavior**
using Go version with CVE

**Environment:**
 - Version of goss 0.4.6
 - OS/Distribution version: alpine linux 3.19

**Comment by ikheifets-splunk** [comment] 2024-05-16 11:15
Hello, @aelsabbahy !
Thank you for PR. When you planning to release it? It would available on 0.4.7?

**Comment by aelsabbahy** [comment] 2024-05-16 14:50
Reopening issue until the release happens. Yes, this will be part of the next goss release.

I should look into automating the trivy checks. :thinking:

**Comment by aelsabbahy** [comment] 2024-05-16 20:40
Released `0.4.7` which should fix this. Feel free to re-open ticket if it doesn't resolve this finding.

**Comment by ikheifets-splunk** [comment] 2024-05-16 20:52
Many thanks @aelsabbahy ! Will test it :)

**Comment by aelsabbahy** [comment] 2024-05-16 21:30
Actually, if you don't mind.. can you show me how to reproduce the failing result on the old version? This way I can look into automating this at a future time.

**Comment by ikheifets-splunk** [comment] 2024-05-16 21:47
Sure, we using [Trivy GitHub action on CI](https://github.com/aquasecurity/trivy-action) which testing our docker image (our open source project is docker image), [results you can see here](https://github.com/splunk/splunk-connect-for-syslog/actions/runs/9067112148/job/24911628742). 

[we just added few lines of code on our CI](https://github.com/splunk/splunk-connect-for-syslog/blob/main/.github/workflows/ci-main.yaml#L157)

**Comment by ikheifets-splunk** [comment] 2024-05-16 22:07
@aelsabbahy I think you can use such command: `trivy repo --tag v0.4.6 https://github.com/goss-org/goss`

**Comment by aelsabbahy** [comment] 2024-05-16 22:24
Perfect, yeah that worked, thanks! Will check out the github actions too.

I tried `trivy fs goss-binary` and got no results earlier, figured I was doing something wrong.

**Comment by ikheifets-splunk** [comment] 2024-05-16 22:50
I also will try yet another time restart this step on CI, they updating CVE database every day, existing small chance that they can reclassify CVE.

[We had last release 3 days ago](https://github.com/splunk/splunk-connect-for-syslog/commits/main/) probably something changed in their db during this time

**Comment by aelsabbahy** [comment] 2024-05-16 22:58
Oh, I just meant it doesn't detect it if you scan the binary directory but does if you scan the repo.

I was confused earlier since I couldn't reproduce your results (due to scanning binary), scanning repo works just fine and I might set up a weekly scan.

Thanks again, this should improve the security posture of Goss!

**Comment by dklimpel** [comment] 2024-05-18 08:01
The scan with trivy GitHub action of goss docker file I had also added to:
- #909

**Comment by aelsabbahy** [comment] 2024-05-18 17:36
Awesome, thanks for all the clarifications, closing.

**Closed by aelsabbahy** 2024-05-18 17:36 UTC
Labels: bug

**Comment by ikheifets-splunk** [comment] 2024-06-25 08:25
@aelsabbahy [trivy](https://trivy.dev) detected another CVE and [I published issue](https://github.com/goss-org/goss/issues/941)
